// City-specific IT corridor locations for CarpoolKaro
export const CITIES = ['Hyderabad', 'Bangalore', 'Pune', 'Mumbai', 'Delhi NCR', 'Chennai']

export const CITY_LOCATIONS = {
  'Hyderabad': [
    'HITEC City','Madhapur','Financial District','Gachibowli','Kokapet','Raidurgam',
    'Kondapur','Manikonda','Narsingi','Nanakramguda','WaveRock SEZ','DLF Cyber City',
    'Mindspace Madhapur','Salarpuria Knowledge City','Divyasree Orion','Khajaguda',
    'Pocharam','Nacharam','Mindspace Pocharam','TCS Synergy Park','Cyberabad',
    'Amazon Hyderabad','Microsoft Campus','Google Hyderabad','Infosys Pocharam',
    'TCS Gachibowli','Wipro Gachibowli','Accenture Gachibowli','Capgemini Gachibowli',
    'Cognizant Gachibowli','Tech Mahindra Gachibowli','IBM Gachibowli',
    'JP Morgan Madhapur','Deloitte Hyderabad','HCL Uppal',
    'Miyapur','KPHB','Kukatpally','Bachupally','Nizampet','Lingampally','Chandanagar',
    'Hafeezpet','Tellapur','Nallagandla','Serilingampally',
    'Jubilee Hills','Banjara Hills','Panjagutta','Film Nagar','Kavuri Hills',
    'Ameerpet','SR Nagar','Somajiguda','Khairatabad','Mehdipatnam','Tolichowki',
    'Secunderabad','Begumpet','Jeedimetla','Balanagar','Kompally','Medchal',
    'Uppal','LB Nagar','Dilsukhnagar','Nagole','Boduppal','Ghatkesar',
    'Miyapur Metro','KPHB Metro','Ameerpet Metro','Hitec City Metro','Raidurg Metro',
    'Nagole Metro','Uppal Metro','LB Nagar Metro','Secunderabad Metro',
    'Rajiv Gandhi International Airport','Shamshabad',
  ],
  'Bangalore': [
    'Whitefield','Marathahalli','Bellandur','Sarjapur Road','Outer Ring Road',
    'Electronic City','Electronic City Phase 1','Electronic City Phase 2',
    'Koramangala','HSR Layout','BTM Layout','Silk Board','Bommanahalli',
    'Hebbal','Manyata Tech Park','Kirloskar Business Park',
    'Yeshwanthpur','Rajajinagar','Tumkur Road','Peenya',
    'Indiranagar','CV Raman Nagar','Domlur','Airport Road',
    'Jayanagar','JP Nagar','Bannerghatta Road','Akshayanagar',
    'Yelahanka','Devanahalli','Kempegowda International Airport',
    'Bagmane Tech Park','RMZ Infinity','Prestige Tech Park',
    'Embassy TechVillage','Cessna Business Park','Ecospace',
    'Microsoft Hyderabad','IBM Manyata','Cisco Bangalore','SAP Bangalore',
    'Amazon Bangalore','Flipkart HQ','Infosys Bangalore','Wipro Sarjapur',
    'HCL Bangalore','TCS Bangalore','Accenture Bangalore',
    'Banashankari','Kanakapura Road','Mysore Road',
    'Rajiv Gandhi Nagar','Hosa Road','Chandapura',
    'MG Road','Church Street','Lavelle Road','Residency Road',
    'Majestic','Shivajinagar','Sadashivanagar',
  ],
  'Pune': [
    'Hinjewadi','Hinjewadi Phase 1','Hinjewadi Phase 2','Hinjewadi Phase 3',
    'Kharadi','Magarpatta','EON IT Park','World Trade Center Pune',
    'Wakad','Baner','Balewadi','Sus Road',
    'Viman Nagar','Kalyani Nagar','Nagar Road',
    'Hadapsar','Fursungi','Uruli Devachi',
    'Aundh','Pimple Saudagar','Pimple Nilakh','Punawale',
    'Shivajinagar','FC Road','JM Road','Deccan',
    'Kothrud','Warje','Karve Road',
    'Yerwada','Koregaon Park','Boat Club Road',
    'Talegaon','Chakan','Ranjangaon',
    'Infosys Pune','Wipro Pune','Cognizant Pune','TCS Pune',
    'Zensar Pune','Tech Mahindra Pune','Persistent Pune',
    'Symbiosis','MIT College Road','SB Road',
    'Katraj','Kondhwa','NIBM Road',
    'Mundhwa','Commerzone','RMZ Westend',
  ],
  'Mumbai': [
    'BKC','Bandra Kurla Complex','Bandra East','Bandra West',
    'Powai','Hiranandani','Chandivali','SEEPZ',
    'Andheri East','Andheri West','MIDC Andheri','Marol',
    'Lower Parel','Worli','Kamala Mills','One BKC',
    'Navi Mumbai','Belapur','Vashi','Nerul','Ghansoli','Mahape',
    'Thane','Wagle Estate','Kolshet','Majiwada',
    'Malad','Mindspace Malad','Link Road',
    'Goregaon','NESCO IT Park','Goregaon East',
    'Vikhroli','Kanjurmarg','LBS Marg',
    'Kurla','Kalina','Santacruz East',
    'Nariman Point','Fort','CSMT','Churchgate',
    'Airoli','Rabale','TTC Industrial Area',
    'Chembur','Ghatkopar','Mulund',
    'Borivali','Kandivali','Dahisar',
    'Chhatrapati Shivaji Airport','CSIA',
    'TCS Yantra Park','Patni Knowledge Center','Cognizant Mumbai',
  ],
  'Delhi NCR': [
    'Noida Sector 62','Noida Sector 63','Noida Sector 125','Noida Sector 132',
    'Noida Sector 135','Noida Sector 136','Noida Sector 142','Noida Sector 143',
    'Noida Expressway','Noida City Centre','Botanical Garden',
    'Gurugram','Gurgaon','Cyber City','DLF Phase 1','DLF Phase 2',
    'DLF Phase 3','DLF Phase 4','DLF Phase 5',
    'Golf Course Road','Sohna Road','NH 8',
    'Udyog Vihar','MG Road Gurgaon','IFFCO Chowk',
    'Manesar','IMT Manesar','KMP Expressway',
    'Greater Noida','Alpha 1','Alpha 2','Beta','Gamma',
    'Knowledge Park','Techzone 4','Surajpur',
    'Connaught Place','Barakhamba','Janpath',
    'Nehru Place','Okhla','Saket','Malviya Nagar',
    'Vasant Kunj','Vasant Vihar','RK Puram',
    'Dwarka','Dwarka Sector 10','Dwarka Sector 21',
    'Rohini','Netaji Subhash Place','Pitampura',
    'Laxmi Nagar','Preet Vihar','IP Extension',
    'IGI Airport','Aerocity',
    'TCS Noida','Infosys Noida','HCL Noida',
    'Accenture Gurgaon','Wipro Gurgaon','IBM Gurgaon',
    'Microsoft Noida','Adobe Noida','Samsung Noida',
  ],
  'Chennai': [
    'OMR','Old Mahabalipuram Road','Sholinganallur','Perungudi','Taramani',
    'Thoraipakkam','Karapakkam','Siruseri','SIPCOT IT Park',
    'Tidel Park','RMZ Millenia','Ascendas IT Park',
    'Anna Nagar','Anna Nagar West','Anna Nagar East',
    'Nungambakkam','Egmore','T Nagar',
    'Velachery','Medavakkam','Pallikaranai',
    'Tambaram','Chrompet','Pallavaram',
    'Porur','Ramapuram','Vadapalani',
    'Guindy','Ekkatuthangal','St Thomas Mount',
    'Ambattur','Ambattur Industrial Estate','SIDCO',
    'Perambur','Villivakkam','Kolathur',
    'Adyar','Besant Nagar','Thiruvanmiyur',
    'Mylapore','Alwarpet','Kotturpuram',
    'Maraimalai Nagar','Mahindra World City',
    'TCS Chennai','Infosys Chennai','Wipro Chennai',
    'Cognizant Chennai','HCL Chennai','Tech Mahindra Chennai',
    'Chennai International Airport',
  ],
}

export function getLocationsForCity(city) {
  return CITY_LOCATIONS[city] || CITY_LOCATIONS['Hyderabad']
}
